name: Generate RSS feeds for Kinobox

on:
  schedule:
    - cron: "0 */4 * * *"  # Tento cron job se spustí každé 4 hodiny
  workflow_dispatch:  # Umožní ti spustit tento workflow ručně z GitHubu

jobs:
  update-feeds:
    name: Update RSS Feeds
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout kódu z repozitáře

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt  # Instalace závislostí

    - name: Generate RSS Feeds
      id: generate_rss_feeds
      run: |
        export LC_ALL="en_US.UTF-8"
        export LC_CTYPE="en_US.UTF-8"
        sudo dpkg-reconfigure locales  # Zajištění správných locale
        python scripts/kinobox_json.py  # Spuštění Python skriptu pro generování RSS

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5  # Automatizovaný commit
      with:
        commit_message: "📝 Update Kinobox RSS Feed"  # Commit zpráva
        commit_options: "--no-gpg-sign"  # Bez GPG podpisu
        branch: main  # Commit na hlavní větev
