name: Generate RSS feeds for CS2 news

on:
  schedule:
    - cron: "30 */4 * * *"
  workflow_dispatch:

jobs:
  update-feeds:
    name: Update RSS-Feeds
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate RSS Feeds
      id: generate_rss_feeds
      run: |
        export LC_ALL="en_US.UTF-8"
        export LC_CTYPE="en_US.UTF-8"
        sudo dpkg-reconfigure locales
        python kinobox_json.py

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "📝 Update RSS News Feed"
        commit_options: "--no-gpg-sign"
        branch: master
