name: Generate Kinobox RSS Feed

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          cd scripts  # Přejít do složky 'scripts'
          pip install -r requirements.txt  # Nainstalovat závislosti

      # Run Python script to generate RSS
      - name: Run Python script to generate RSS
        run: |
          cd scripts  # Přejít do složky 'scripts'
          python kinobox_json.py  # Spustit Python skript

      # Commit and push the generated RSS feed back to the repository
      - name: Commit and push RSS feed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add kinobox_trendy_rss.xml  # Ujisti se, že soubor je správně uložen
          git commit -m "Update RSS feed"
          git push origin main  # Push zpět do repozitáře
