name: Generate RSS feeds for Kinobox

on:
  schedule:
    - cron: "0 */4 * * *"  # This cron job runs every 4 hours
  workflow_dispatch:  # Allows you to trigger this workflow manually from GitHub

jobs:
  update-feeds:
    name: Update RSS Feeds
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout kódu z repozitáře

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt  # Instalace závislostí

    - name: Generate RSS Feeds
      id: generate_rss_feeds
      env: # <--- Zde přidáváme proměnné prostředí z GitHub Secrets
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
        # Volitelně můžete přidat i další proměnné prostředí pro locale, pokud jsou opravdu potřeba
        # a předchozí exporty nestačily. Ale často stačí jen nastavit LANG a LC_ALL.
        LANG: en_US.UTF-8
        LC_ALL: en_US.UTF-8
      run: |
        # Následující řádky pro locale jsou většinou zbytečné v GitHub Actions,
        # protože prostředí je již nastaveno a sudo není doporučeno, pokud není nezbytně nutné.
        # export LC_ALL="en_US.UTF-8"
        # export LC_CTYPE="en_US.UTF-8"
        # sudo dpkg-reconfigure locales
        
        # Spuštění vašich Python skriptů
        python scripts/kinobox_novinky_json.py
        python scripts/tmdb_popular.py
        # python scripts/tmdb_tv.py
        

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5  # Automatizovaný commit
      with:
        commit_message: "📝Aktualizace RSS kanálu"  # Commit zpráva
        commit_options: "--no-gpg-sign"  # Bez GPG podpisu
        branch: main  # Commit na hlavní větev
